// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL_nAIdaWs8f7B6AhD4h4dV7mYamjVtkg',
    appId: '1:876237732305:web:188704ea378d60741c48f0',
    messagingSenderId: '876237732305',
    projectId: 'watch-app-62e07',
    authDomain: 'watch-app-62e07.firebaseapp.com',
    storageBucket: 'watch-app-62e07.firebasestorage.app',
    measurementId: 'G-HGSQLSMFJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcxTD5Z-mKXA5u0-EOcyFtB-h4jJLPK3M',
    appId: '1:876237732305:android:b8866376df9312161c48f0',
    messagingSenderId: '876237732305',
    projectId: 'watch-app-62e07',
    storageBucket: 'watch-app-62e07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF9dMND1JajVRxP_p8DN1Eq43xt5vr81s',
    appId: '1:876237732305:ios:d8a42987572d90901c48f0',
    messagingSenderId: '876237732305',
    projectId: 'watch-app-62e07',
    storageBucket: 'watch-app-62e07.firebasestorage.app',
    iosBundleId: 'com.example.prm8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF9dMND1JajVRxP_p8DN1Eq43xt5vr81s',
    appId: '1:876237732305:ios:d8a42987572d90901c48f0',
    messagingSenderId: '876237732305',
    projectId: 'watch-app-62e07',
    storageBucket: 'watch-app-62e07.firebasestorage.app',
    iosBundleId: 'com.example.prm8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL_nAIdaWs8f7B6AhD4h4dV7mYamjVtkg',
    appId: '1:876237732305:web:5f1184a27ac16b721c48f0',
    messagingSenderId: '876237732305',
    projectId: 'watch-app-62e07',
    authDomain: 'watch-app-62e07.firebaseapp.com',
    storageBucket: 'watch-app-62e07.firebasestorage.app',
    measurementId: 'G-94ZZJ5DHPB',
  );
}
